CREATE TABLE PATIENT (
    ID NUMBER(19) NOT NULL,
    FULL_NAME VARCHAR2(120 CHAR) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    CONSTRAINT PK_PATIENT PRIMARY KEY (ID),
    CONSTRAINT CK_PATIENT_BIRTH_DATE CHECK (DATE_OF_BIRTH < TRUNC(SYSDATE))
);

CREATE SEQUENCE SEQ_PATIENT START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE PROCEDURE P_PATIENT_AGE (
    p_patient_id IN PATIENT.ID%TYPE,
    p_age_years OUT NUMBER
) AS
BEGIN
    SELECT TRUNC(MONTHS_BETWEEN(TRUNC(SYSDATE), DATE_OF_BIRTH) / 12)
      INTO p_age_years
      FROM PATIENT
     WHERE ID = p_patient_id;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001, 'Paciente não encontrado');
END;
/

INSERT INTO PATIENT (ID, FULL_NAME, DATE_OF_BIRTH) VALUES (SEQ_PATIENT.NEXTVAL, 'Ana Oliveira', DATE '1992-04-15');
INSERT INTO PATIENT (ID, FULL_NAME, DATE_OF_BIRTH) VALUES (SEQ_PATIENT.NEXTVAL, 'Carlos Santos', DATE '1985-11-03');
COMMIT;
